# Generated by Django 5.2.18 on 2026-10-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0002_moneda_fecha_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor nominal')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='monedas.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Denominación',
                'verbose_name_plural': 'Denominaciones',
                'db_table': 'denominaciones',
                'ordering': ['moneda', 'valor'],
                'constraints': [models.UniqueConstraint(fields=('moneda', 'valor'), name='unique_denominacion_moneda_valor'), models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='check_denominacion_valor_positivo')],
            },
        ),
    ]
