# Generated by Django 5.2.17 on 2026-09-01 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('CUENTA_BANCARIA', 'Cuenta Bancaria'), ('BILLETERA_DIGITAL', 'Billetera Digital')], max_length=30)),
                ('alias', models.CharField(help_text='Nombre descriptivo (ej: Mi Visa ITAU)', max_length=50)),
                ('numero_cuenta_o_tarjeta', models.CharField(help_text='Número o alias/CBU codificado', max_length=50)),
                ('banco_o_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
