# Generated by Django 5.2.17 on 2026-09-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediopago',
            name='alias',
            field=models.CharField(help_text='Nombre del medio de pago (ej: Transferencia Bancaria)', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='numero_cuenta_o_tarjeta',
            field=models.CharField(blank=True, help_text='Número o alias/CBU codificado', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='tipo',
            field=models.CharField(blank=True, choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('CUENTA_BANCARIA', 'Cuenta Bancaria'), ('BILLETERA_DIGITAL', 'Billetera Digital')], max_length=30),
        ),
    ]
