# Generated by Django 5.2.17 on 2026-09-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_pago', '0003_metodos_pago_especificos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediopago',
            name='tipo',
            field=models.CharField(blank=True, choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('CUENTA_BANCARIA', 'Cuenta Bancaria'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('BILLETERA_DIGITAL', 'Billetera Digital')], max_length=30),
        ),
    ]
