# Generated by Django 5.2.17 on 2026-08-30 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Jurídica', 'Jurídica'), ('Física', 'Física')], max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('cuenta_acreditar', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='clientes_asociados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
