# Generated by Django 5.2.17 on 2026-09-04 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('comisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.ForeignKey(blank=True, help_text='Segmento comercial del que sale el porcentaje de comisión.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='comisiones.segmentocliente'),
        ),
    ]
