# Generated by Django 5.2.17 on 2026-09-04 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del segmento. Por ejemplo: VIP, Corporativo, Minorista.', max_length=50, unique=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, help_text='Porcentaje que se le cobra a este segmento, entre 0 y 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'segmento de cliente',
                'verbose_name_plural': 'segmentos de cliente',
                'ordering': ['porcentaje_comision', 'nombre'],
            },
        ),
    ]
