# Generated by Django 5.2.17 on 2026-09-01 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='monedas.moneda')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
