# Generated by Django 5.2.17 on 2026-10-02 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_segmento'),
        ('cotizaciones', '0002_historialcotizacion'),
        ('medios_pago', '0005_tipomediopago'),
        ('monedas', '0002_moneda_fecha_actualizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra de divisa'), ('VENTA', 'Venta de divisa')], max_length=10)),
                ('monto_divisa', models.DecimalField(decimal_places=2, help_text='Cantidad de divisa que el cliente compra o vende.', max_digits=14)),
                ('tasa_base', models.DecimalField(decimal_places=2, help_text='Precio de venta (si el cliente compra) o de compra (si vende).', max_digits=12)),
                ('descuento_compra', models.DecimalField(decimal_places=2, default=0, help_text='Descuento del segmento del cliente, entre 0 y 1. Solo en compras.', max_digits=4)),
                ('tasa_aplicada', models.DecimalField(decimal_places=4, help_text='Tasa base con el descuento del segmento ya aplicado.', max_digits=14)),
                ('monto_guaranies', models.DecimalField(decimal_places=0, help_text='Monto de divisa por la tasa aplicada, antes de la comisión.', max_digits=16)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión del segmento, entre 0 y 100.', max_digits=5)),
                ('comision', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('total_guaranies', models.DecimalField(decimal_places=0, help_text='Lo que paga el cliente (compra) o lo que recibe (venta).', max_digits=16)),
                ('medio_pago_descripcion', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=200)),
                ('cancelada_por_cotizacion', models.BooleanField(default=False)),
                ('tasa_base_nueva', models.DecimalField(blank=True, decimal_places=2, help_text='Precio vigente que se encontró al intentar pagar. Vacío si ya no había cotización.', max_digits=12, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='clientes.cliente')),
                ('cotizacion', models.ForeignKey(blank=True, help_text='Cotización vigente al crear la operación. Solo como referencia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='cotizaciones.cotizacion')),
                ('medio_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='medios_pago.mediopago')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='monedas.moneda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transacción',
                'verbose_name_plural': 'transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
