# Generated by Django 5.2.17 on 2026-09-25 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0002_moneda_fecha_actualizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion_congelada', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('COMPLETADA', 'Completada'), ('CANCELADA_COTIZACION', 'Cancelada por cambio de cotización'), ('EXPIRADA', 'Expirada')], default='PENDIENTE_PAGO', max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
                ('moneda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='monedas.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='monedas.moneda')),
            ],
        ),
    ]
